### ISSUE TITLE
Flutter App TODO List

### ISSUE THREAD

**Issue by Stimim** [yjlou/2019-nCov#15]
- [x] Check against patient data
  - [x] Define server side API (could be static file(s))
  - [x] Fetch patient data from server
  - [x] Parse patient data
  - [x] Compare patient data with local data
- [ ] Export collected locations
  - [x] Export decrypted database
  - [ ] Export encrypted database (do we need this? are there any use cases?)
- [x] Polish UI
  - [x] Ask again before deleting database

**Comment by Stimim** [comment]
Critical features should have been implemented now.

Known issue(s) / Next steps:

- [ ] Because we are not using "Navigator", pressing "back" button will leave the app.
  - I feel that using Navigator is causing more issues than it solve.
- [ ] i18n support
- [ ] Show more records in "recorded_location_widget"
- [x] Should we go to "matched_result_widget" when "check now" is clicked?
- [x] Periodic check won't update "last checked" on UI.
- [x] Save selected locale in shared preferences.
